// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.960
package cluster

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

// InstructionsCard renders role-based Cluster guidance.
func InstructionsCard(isHost bool, compact bool) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<details class=\"bg-elevated border border-border rounded p-4 sm:p-5\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !compact {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, " open")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "><summary class=\"cursor-pointer list-none font-mono text-xs tracking-widest uppercase text-cyan\">Help: How Cluster Works</summary><div class=\"space-y-4 mt-4 text-sm\"><div><p class=\"text-text font-medium\">Goal</p><p class=\"text-text-muted mt-1\">Place your point where you think the group will land. Closest to centroid wins.</p></div><div><p class=\"text-text font-medium\">Round Flow</p><ul class=\"space-y-1 text-text-muted mt-1\"><li>1. Read the prompt and axis labels.</li><li>2. Pick one coordinate on the plane and submit.</li><li>3. After everyone submits, centroid and scores are revealed.</li><li>4. Host advances to the next prompt.</li></ul></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if isHost {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "<div class=\"rounded border border-amber/40 bg-amber/10 p-3\"><p class=\"font-mono text-[11px] uppercase tracking-widest text-amber\">Host actions</p><p class=\"text-text-muted mt-1\">Start the session, skip weak prompts when needed, and move the group to the next round.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		} else {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div class=\"rounded border border-cyan/30 bg-cyan/10 p-3\"><p class=\"font-mono text-[11px] uppercase tracking-widest text-cyan\">Player actions</p><p class=\"text-text-muted mt-1\">Submit one point per round and compare your choice to the centroid reveal.</p></div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "<div><p class=\"text-text font-medium\">Example turn</p><p class=\"text-text-muted mt-1\">If the prompt is about celebrations, pick your spot between low/high energy and practical/aspirational, then discuss differences after reveal.</p></div></div></details>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
