// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lobbies.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLobby = `-- name: CreateLobby :one
INSERT INTO lobbies (code, name)
VALUES ($1, $2)
RETURNING id, code, name, created_at, game_type, phase
`

type CreateLobbyParams struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

func (q *Queries) CreateLobby(ctx context.Context, arg CreateLobbyParams) (Lobby, error) {
	row := q.db.QueryRow(ctx, createLobby, arg.Code, arg.Name)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.GameType,
		&i.Phase,
	)
	return i, err
}

const deleteLobby = `-- name: DeleteLobby :exec
DELETE FROM lobbies WHERE id = $1
`

func (q *Queries) DeleteLobby(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLobby, id)
	return err
}

const getLobbyByCode = `-- name: GetLobbyByCode :one
SELECT id, code, name, created_at, game_type, phase FROM lobbies WHERE code = $1
`

func (q *Queries) GetLobbyByCode(ctx context.Context, code string) (Lobby, error) {
	row := q.db.QueryRow(ctx, getLobbyByCode, code)
	var i Lobby
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.CreatedAt,
		&i.GameType,
		&i.Phase,
	)
	return i, err
}

const listLobbies = `-- name: ListLobbies :many
SELECT id, code, name, created_at, game_type, phase FROM lobbies ORDER BY created_at DESC
`

func (q *Queries) ListLobbies(ctx context.Context) ([]Lobby, error) {
	rows, err := q.db.Query(ctx, listLobbies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lobby{}
	for rows.Next() {
		var i Lobby
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.CreatedAt,
			&i.GameType,
			&i.Phase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
