// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Lobby struct {
	ID        pgtype.UUID        `json:"id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	GameType  string             `json:"game_type"`
	Phase     string             `json:"phase"`
}

type LobbyPlayer struct {
	ID       pgtype.UUID        `json:"id"`
	LobbyID  pgtype.UUID        `json:"lobby_id"`
	PlayerID pgtype.UUID        `json:"player_id"`
	Nickname string             `json:"nickname"`
	IsHost   bool               `json:"is_host"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type Player struct {
	ID          pgtype.UUID        `json:"id"`
	DeviceToken string             `json:"device_token"`
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TriviaAnswer struct {
	ID             pgtype.UUID        `json:"id"`
	QuestionID     pgtype.UUID        `json:"question_id"`
	PlayerID       pgtype.UUID        `json:"player_id"`
	SelectedAnswer string             `json:"selected_answer"`
	IsCorrect      bool               `json:"is_correct"`
	AnsweredAt     pgtype.Timestamptz `json:"answered_at"`
}

type TriviaQuestion struct {
	ID            pgtype.UUID        `json:"id"`
	RoundID       pgtype.UUID        `json:"round_id"`
	Author        pgtype.UUID        `json:"author"`
	QuestionText  string             `json:"question_text"`
	CorrectAnswer string             `json:"correct_answer"`
	WrongAnswer1  string             `json:"wrong_answer_1"`
	WrongAnswer2  string             `json:"wrong_answer_2"`
	WrongAnswer3  string             `json:"wrong_answer_3"`
	DisplayOrder  pgtype.Int4        `json:"display_order"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type TriviaRound struct {
	ID          pgtype.UUID        `json:"id"`
	LobbyID     pgtype.UUID        `json:"lobby_id"`
	RoundNumber int32              `json:"round_number"`
	Phase       string             `json:"phase"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}
